# [AUTO-GENERATED by Admin Dashboard]
# Last updated: 2026-04-02 16:45:41
# Domain count: 20

DOMAIN_POOL = [
    "logistics-dynamics.kr",
    "polymer-cleaning.co.kr",
    "net-scan.cloud",
    "infra-maintenance.kr",
    "fluid-flow.xyz",
    "standard-eco.life",
    "system-gate.xyz",
    "data-grid.cloud",
    "code-lab.shop",
    "base-camp.shop",
    "move-easy.xyz",
    "home-care.shop",
    "apt-clean.shop",
    "clean-all.xyz",
    "quick-move.shop",
    "clean-pro.xyz",
    "ok-check.xyz",
    "yes-data.xyz",
    "now-on.xyz",
    "link-us.shop",
]
